name: building_blocks
description: A flutter project contains reusable blocks/components to build an
  app's user experience.
version: 1.0.0+1

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.24.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  responsive_layout:
    path: packages/responsive_layout

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
