name: building_blocks

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
      - ".github/workflows/main.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
      - ".github/workflows/main.yaml"

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: "3.24.1"

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
      modified_files_only: false
